### ISSUE TITLE
Paho client disconnected due to 'Timed out waiting for a response from the server (32000)' 

### ISSUE THREAD

**Issue by HJianBo** [emqx/emqx#10658]
### What happened?

Through the test scenarios provided by ___, we have reproduced the disconnected issues on EMQX.

The following log was reported after the Paho disconnected:
```
10:23:07.498 [MQTT Ping: demo_mqtt_001] INFO com.xuanyu.demo.mqttdemo.MqttSubscriber - Reconnect to broker successfully, client id: demo_mqtt_001
May 10, 2023 10:23:07 AM org.eclipse.paho.client.mqttv3.internal.ClientState checkForActivity
SEVERE: demo_mqtt_001: Timed out as no activity, keepAlive=30,000,000,000 lastOutboundActivity=467,138,114,723,984 lastInboundActivity=467,108,162,493,786 time=467,168,117,810,461 lastPing=467,138,114,729,988
Timed out waiting for a response from the server (32000)
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.checkForActivity(ClientState.java:747)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:818)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:804)
	at org.eclipse.paho.client.mqttv3.TimerPingSender$PingTask.run(TimerPingSender.java:79)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
May 10, 2023 10:24:22 AM org.eclipse.paho.client.mqttv3.internal.ClientState checkForActivity
SEVERE: demo_mqtt_001: Timed out as no activity, keepAlive=30,000,000,000 lastOutboundActivity=467,213,494,984,848 lastInboundActivity=467,183,554,541,715 time=467,243,500,206,305 lastPing=467,213,494,989,215
Timed out waiting for a response from the server (32000)
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.checkForActivity(ClientState.java:747)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:818)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:804)
	at org.eclipse.paho.client.mqttv3.TimerPingSender$PingTask.run(TimerPingSender.java:79)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

### What did you expect to happen?

No longer disconnected due to heartbeat timeout

### How can we reproduce it (as minimally and precisely as possible)?

Reproduce according to the example provided by the ___

### Anything else we need to know?

![image](https://github.com/emqx/emqx/assets/13825269/d022ac6a-128d-40fe-9f66-b3cecbc835d3)

Through my local reproduction and analysis, I find the root cause:

1. When the Paho client connects to EMQX, due to a large number of messages still present in the session, EMQX will immediately resend the entire flight window data (approximately 32*50000B = ~1.52MB) after replying to a CONNACK.

2. The sample code calls the `subscribe` function in the `connectComplete` callback, but this function is blocking and needs to wait for EMQX to reply with SUBACK before returning.

3. After Paho blocks, it can no longer receive messages from TCP Buffer, causing EMQX to exhaust the TCP Window due to it delivering all messages of the Inflight Window at once.

4. Now a deadlock occurs where EMQX is waiting for TCP Window recovery while Paho is waiting for a response from SUBACK.

### EMQX version

EMQX v5.0.24

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>

</details>

**Comment by qzhuyan** [comment]
I think it is a bug at client side. C
lient should not stop handle packets from transport while waiting for suback after reconnect without clean session or drain the messages from session.

**Comment by nilong-project** [comment]
Does emqx have a plan to fix this? The paho.mqtt client has not been released in a new version for a long time, and it seems that they will not fix this issue again.thank you

**Comment by zmstone** [comment]
This is an application bug, not a Paho bug.

The deadlock comes from calling the blocking subscribe() inside the connectComplete callback. 
Paho documents that callbacks must not block, so the library is behaving as designed here.

Two application-side fixes, either of which breaks the cycle:

1. Don't block in the callback. I don't know paho java lib well, but there must be a non-blocking variant. This works regardless of session state.
2. Skip the subscribe when the session was resumed. With cleanSession=false, subscriptions are part of the persisted session, so re-subscribing after a reconnect is redundant.

Fix (1) alone is sufficient and is the more robust of the two.

I close this issue. 
EMQX can be enhanced to mitigate, let's follow up here: https://github.com/emqx/emqx/issues/18460
