### ISSUE TITLE
Connection lost  java.io.EOFException

### ISSUE THREAD

**Issue by Fyee** [emqx/emqx#11058]
### What happened?

The error message is as follows
```log
19:19:35.020  D  Connection lost 已断开连接 (32109) - java.io.EOFException
19:19:35.021  D  已断开连接 (32109) - java.io.EOFException
                  at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
                  at java.lang.Thread.run(Thread.java:919)
                 Caused by: java.io.EOFException
                  at java.io.DataInputStream.readByte(DataInputStream.java:270)
                  at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
                  at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
                  at java.lang.Thread.run(Thread.java:919)
```
This is my code.
```kt
import org.eclipse.paho.android.service.MqttAndroidClient
import org.eclipse.paho.client.mqttv3.*

class Mqtt{
    private lateinit var mqttClient: MqttAndroidClient
    private var TAG = "AndroidMqttClient"
    val topic = "${Attendance.Mqtt.TOPIC_NOTICE}${ToolsUtil.getSN()}"

    fun connect(
        callBack: IPush.Callback
    ) {
        val serverURI = Constants.MQTT_SERVER_URI
        val username = Constants.MQTT_USERNAME
        val password = Constants.MQTT_PASSWORD
        LogUtil.d(TAG,"mqtt:serverUri:$serverURI username:$username password:$password clientId:${ToolsUtil.getSN()}")

        mqttClient = MqttAndroidClient(BaseApplication.getApp(), serverURI, ToolsUtil.getSN())
        mqttClient.setCallback(object : MqttCallbackExtended {
            override fun messageArrived(topic: String?, message: MqttMessage?) {
                Log.d(TAG, "Receive message: ${message.toString()} from topic: $topic")
                callBack.onReceiveData(message.toString())
            }

            override fun connectionLost(cause: Throwable?) {
                Log.d(TAG, "Connection lost ${cause.toString()}")
                callBack.onState(false)
            }

            override fun deliveryComplete(token: IMqttDeliveryToken?) {

            }

            override fun connectComplete(reconnect: Boolean, serverURI: String?) {
                Log.d(TAG, "connectComplete reconnect $reconnect serverURI $serverURI")
                Log.d(TAG, "Connection success")
                subscribe(topic)
                val msg = HexUtil.setRequestStr(
                    Constants.BIND,
                    HexUtil.string2HexString(ToolsUtil.getSN())
                )
                publish("device/onLine", msg, 1, false)
            }
        })
        val options = MqttConnectOptions()
        options.userName = username
        options.password = password.toCharArray()
        options.connectionTimeout = MqttConnectOptions.CONNECTION_TIMEOUT_DEFAULT
        options.keepAliveInterval = MqttConnectOptions.KEEP_ALIVE_INTERVAL_DEFAULT
        options.isAutomaticReconnect = true
        //离线
        val offlineMsg = HexUtil.setRequestStr(
            Constants.BIND,
            HexUtil.string2HexString(ToolsUtil.getSN())
        )
        options.setWill(Attendance.Mqtt.TOPIC_DEVICE_OFFLINE, offlineMsg.toByteArray(), 2, false)

        try {
            if (!mqttClient.isConnected) {
                realConn(options, callBack)
            } else {
                mqttClient.disconnect()
                realConn(options, callBack)
            }
        } catch (e: MqttException) {
            e.printStackTrace()
            Log.d(TAG,"${e.message}")
        }

    }

    fun isConnected() = mqttClient.isConnected


    private fun realConn(
        options: MqttConnectOptions,
        callBack: IPush.Callback
    ) {
        mqttClient.connect(options, null, object : IMqttActionListener {
            override fun onSuccess(asyncActionToken: IMqttToken?) {
                callBack.onState(true)
            }

            override fun onFailure(asyncActionToken: IMqttToken?, exception: Throwable?) {
                Log.d(TAG, "Connection failure:${exception?.message} ${String(options.password)}")
                callBack.onState(false)
            }
        })
    }

    fun subscribe(topic: String, qos: Int = 1) {
        try {
            mqttClient.subscribe(topic, qos, null)
        } catch (e: MqttException) {
            e.printStackTrace()
            Log.d(TAG,"${e.message}")
        }
    }

    fun unsubscribe(topic: String) {
        try {
            mqttClient.unsubscribe(topic, null, object : IMqttActionListener {
                override fun onSuccess(asyncActionToken: IMqttToken?) {
                    Log.d(TAG, "Unsubscribed to $topic")
                }

                override fun onFailure(asyncActionToken: IMqttToken?, exception: Throwable?) {
                    Log.d(TAG, "Failed to unsubscribe $topic")
                }
            })
        } catch (e: MqttException) {
            e.printStackTrace()
            Log.d(TAG,"${e.message}")
        }
    }

    fun publish(topic: String, msg: String, qos: Int = 1, retained: Boolean = false) {
        try {
            val message = MqttMessage()
            message.payload = msg.toByteArray()
            message.qos = qos
            message.isRetained = retained
            mqttClient.publish(topic, message, null, object : IMqttActionListener {
                override fun onSuccess(asyncActionToken: IMqttToken?) {
                    Log.d(TAG, "$msg published to $topic")
                }

                override fun onFailure(asyncActionToken: IMqttToken?, exception: Throwable?) {
                    Log.d(TAG, "Failed to publish $msg to $topic")
                }
            })
        } catch (e: MqttException) {
            e.printStackTrace()
            Log.d(TAG,"${e.message}")
        }
    }


    fun disconnect() {
        try {
            mqttClient.disconnect(null, object : IMqttActionListener {
                override fun onSuccess(asyncActionToken: IMqttToken?) {
                    Log.d(TAG, "Disconnected")
                }

                override fun onFailure(asyncActionToken: IMqttToken?, exception: Throwable?) {
                    Log.d(TAG, "Failed to disconnect")
                }
            })
        } catch (e: MqttException) {
            e.printStackTrace()
            Log.d(TAG,"${e.message}")
        }
    }
}

```

### What did you expect to happen?

I'm using the WSS protocol, and sometimes the connection is interrupted. I hope to maintain a stable connection.

### EMQX version

'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.4'

### Log files

<details>

</details>

**Comment by zmstone** [comment]
Could you provide the logs in EMQX ?
Maybe enable debug level logging or make use of the "trace" feature to capture all the events of a disconnecting client.
