### ISSUE TITLE
Java1.6 SSL connect EMQ  MqttException (0) - javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

### ISSUE THREAD

**Issue by hyman-hu** [emqx/emqx#2489]
java version: jdk-6u45-windows-x64.exe
EMQ Version: emqttd-windows7-v2.3.6.zip

MqttException (0) - javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:690)
	at java.lang.Thread.run(Thread.java:662)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:882)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1188)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1215)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1199)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:97)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:676)
	... 1 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:462)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:863)
	... 6 more

**Comment by hyman-hu** [comment]
jdk1.8 It's normal

**Comment by hyman-hu** [comment]
EQM config is default config

**Comment by Gilbert-Wong** [comment]
I suggest you to build your `mqtt` java client with jdk 1.8. I'm not familiar with java. But I suppose that the jdk 1.6 is too old, and maybe there is functional limitation in the ssl library of jdk 1.6.

**Comment by hyman-hu** [comment]
I know. I wonder if it can be fixed?

**Comment by hyman-hu** [comment]
I know. I wonder if I can solve this problem

**Comment by jinfahua** [comment]
It's probably a TLS version problem (the TLS version is too lower in JRE 1.6). You can use Wireshark to capture the MQTT packets between your JRE 1.6 client and EMQ server to verify the problem. If you have to use JRE 1.6, you could refer to the link  https://community.developer.visa.com/t5/Developer-Tools/Upgrade-to-TLS-1-2-Let-security-be-part-of-your-development/ba-p/6691 for more information.
