### ISSUE TITLE
[error] crasher when publish message through paho with tcp

### ISSUE THREAD

**Issue by HsinWong** [emqx/emqx#3250]
#### Environment

- OS: CentOS  7.6.1810
- Erlang/OTP: 
- EMQ: 3.0.1
- Paho: 1.2.1

#### Description

From a certain point in time, publishing message through paho with tcp would get exception below, and it happens 100%. Until i restart emqx service:

`org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:189)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:136)
	... 1 common frames omitted`

emqx error logs:

```
2020-02-17 00:14:32.303 [error] ccr-mqtt-master-iZbp1dfsc09po8joyd7obzZ@9000-SIGNAL-emqx@10.27.69.51@10.31.120.167:55154 WebHook: Client disconnected, cannot encode reason: {noproc,
                                                     {gen_server,call,
                                                      [<0.1817.0>,
                                                       {register_publish_packet_id,
                                                        1,
                                                        {1581,869672,303749}},
                                                       infinity]}}
2020-02-17 00:14:32.307 [error] ccr-mqtt-master-iZbp1dfsc09po8joyd7obzZ@9000-SIGNAL-emqx@10.27.69.51@10.31.120.167:55154 ** Generic server <0.4042.1742> terminating 
** Last message in was {tcp,#Port<0.163884653>,
                            <<53,16,0,12,114,111,111,109,47,55,54,50,47,119,
                              101,98,0,1>>}
** When Server state == {state,esockd_transport,#Port<0.163884653>,
                            {{10,31,120,167},55154},
                            undefined,running,100,
                            {pstate,external,
                                #Fun<emqx_connection.0.118827427>,
                                {{10,31,120,167},55154},
                                nossl,4,<<"MQTT">>,
                                <<"ccr-mqtt-master-iZbp1dfsc09po8joyd7obzZ@9000-SIGNAL-emqx@10.27.69.51">>,
                                false,<0.4042.1742>,undefined,undefined,
                                <<"d48af0d9-7972-4047-bc2d-6c4c710d909a">>,
                                <0.1817.0>,false,#{},10485760,7,undefined,
                                false,false,true,true,ignore,
                                #{msg => 0,pkt => 3},
                                #{msg => 0,pkt => 3},
                                true,
                                {1581,869657,902591},
                                false,
                                #{from_client => 0,to_client => 0}},
                            {none,#{max_packet_size => 10485760,version => 4}},
                            {emqx_gc,
                                #{cnt => {1000,997},oct => {1048576,1048430}}},
                            {keepalive,#Fun<emqx_connection.7.118827427>,144,
                                5,
                                {keepalive,check},
                                #Ref<0.1103605129.3018588161.13963>,0},
                            true,#Ref<0.1103605129.3018588161.10262>,
                            undefined,undefined,undefined,15000}
** Reason for termination == 
** {{noproc,{gen_server,call,
                        [<0.1817.0>,
                         {register_publish_packet_id,1,{1581,869672,303749}},
                         infinity]}},
    [{gen_server,call,3,[{file,"gen_server.erl"},{line,223}]},
     {emqx_session,publish,3,[{file,"src/emqx_session.erl"},{line,262}]},
     {emqx_protocol,do_publish,2,[{file,"src/emqx_protocol.erl"},{line,556}]},
     {emqx_connection,handle_packet,2,
                      [{file,"src/emqx_connection.erl"},{line,352}]},
     {emqx_connection,process_incoming,2,
                      [{file,"src/emqx_connection.erl"},{line,332}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2020-02-17 00:14:32.329 [error] ccr-mqtt-master-iZbp1dfsc09po8joyd7obzZ@9000-SIGNAL-emqx@10.27.69.51@10.31.120.167:55154 crasher:
    initial call: emqx_connection:init/1
    pid: <0.4042.1742>
    registered_name: []
    exception exit: {noproc,
                        {gen_server,call,
                            [<0.1817.0>,
                             {register_publish_packet_id,1,
                                 {1581,869672,303749}},
                             infinity]}}
      in function  gen_server:call/3 (gen_server.erl, line 223)
      in call from emqx_session:publish/3 (src/emqx_session.erl, line 262)
      in call from emqx_protocol:do_publish/2 (src/emqx_protocol.erl, line 556)
      in call from emqx_connection:handle_packet/2 (src/emqx_connection.erl, line 352)
      in call from emqx_connection:process_incoming/2 (src/emqx_connection.erl, line 332)
      in call from gen_server:try_dispatch/4 (gen_server.erl, line 637)
      in call from gen_server:handle_msg/6 (gen_server.erl, line 711)
    ancestors: [<0.1620.0>,<0.1619.0>,esockd_sup,<0.1334.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1620.0>]
    dictionary: [{{publish,<<"room/762/web">>},{allow,1581869672303}},
                  {'$logger_metadata$',
                      #{client_id =>
                            <<"ccr-mqtt-master-iZbp1dfsc09po8joyd7obzZ@9000-SIGNAL-emqx@10.27.69.51">>,
                        peername => "10.31.120.167:55154"}},
                  {incoming_bytes,164},
                  {guid,{1581869672303874,59544588128202,2}},
                  {rand_seed,
                      {#{bits => 58,jump => #Fun<rand.8.10897371>,
                         next => #Fun<rand.5.10897371>,type => exrop,
                         uniform => #Fun<rand.6.10897371>,
                         uniform_n => #Fun<rand.7.10897371>,
                         weak_low_bits => 1},
                       [202451697973782729|265308300767928811]}},
                  {force_shutdown_policy,
                      #{max_heap_size => 134217728,message_queue_len => 1000}},
                  {'$metrics',
                      #{{counter,'bytes/received'} => 164,
                        {counter,'bytes/sent'} => 8}},
                  {incoming_pubs,1},
                  {acl_cache_size,1},
                  {acl_keys_q,{[{publish,<<"room/762/web">>}],[]}}]
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 27
    reductions: 965022
  neighbours:
2020-02-17 00:14:32.340 [error] supervisor: 'esockd_connection_sup - <0.1620.0>'
    errorContext: connection_crashed
    reason: {noproc,
                {gen_server,call,
                    [<0.1817.0>,
                     {register_publish_packet_id,1,{1581,869672,303749}},
                     infinity]}}
    offender: [{pid,<0.4042.1742>},
               {name,connection},
               {mfargs,
                   {emqx_connection,start_link,
                       [[{max_conn_rate,1000},
                         {active_n,100},
                         {zone,external}]]}}]
```

**Comment by tigercl** [comment]
@HsinWong  emqx v3.0.1 is an earlier version, and we have fixed many issues later. You can try changing to newer versions like emqx v3.2.7 and v 4.0.2.
