### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid UTF-8 char: [d869]

### ISSUE THREAD

**Issue by blue-aurora** [emqx/emqx#3590]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): EMQ X Broker 3.2.7
- Hardware configuration (e.g. `lscpu`): 16CPU 32RAM
- OS (e.g. `cat /etc/os-release`): centos 7.6
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): rpm install
- Others:

**What happened and what you expected to happen**:
The following error is reported during normal use, and then emqx can never be connected again！

Exception in thread "MQTT Rec: xxxxxx" java.lang.IllegalArgumentException: Invalid UTF-8 char: [d869]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.validateUTF8String(MqttWireMessage.java:407)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.decodeUTF8(MqttWireMessage.java:365)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttPublish.<init>(MqttPublish.java:64)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.createWireMessage(MqttWireMessage.java:207)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.createWireMessage(MqttWireMessage.java:182)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:119)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wwhai** [comment]
> **Environment**:
> 
> * EMQ X version (e.g. `emqx_ctl status`): EMQ X Broker 3.2.7
> * Hardware configuration (e.g. `lscpu`): 16CPU 32RAM
> * OS (e.g. `cat /etc/os-release`): centos 7.6
> * Kernel (e.g. `uname -a`):
> * Erlang/OTP version (in case you build emqx from source code): rpm install
> * Others:
> 
> **What happened and what you expected to happen**:
> The following error is reported during normal use, and then emqx can never be connected again！
> 
> Exception in thread "MQTT Rec: xxxxxx" java.lang.IllegalArgumentException: Invalid UTF-8 char: [d869]
> at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.validateUTF8String(MqttWireMessage.java:407)
> at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.decodeUTF8(MqttWireMessage.java:365)
> at org.eclipse.paho.client.mqttv3.internal.wire.MqttPublish.(MqttPublish.java:64)
> at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.createWireMessage(MqttWireMessage.java:207)
> at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.createWireMessage(MqttWireMessage.java:182)
> at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:119)
> at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
> at java.lang.Thread.run(Thread.java:748)

Can show your Java-Paho-Mqtt program for us?
