### ISSUE TITLE
Subscribing successfully but receiving message unsuccessfully with cleanSession=false

### ISSUE THREAD

**Issue by RichardChengshaojin** [emqx/emqx#3779]
**Environment**

- OS: CentOS Linux release 7.5.1804 (Core) 
- Erlang/OTP: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.0
- EMQ: emqx broker v3.0.1

**Description**

How do I get the problem:

1. Subscribe a topic with connection option `cleanSession=false`
2. Start the consumer client
3. Produce a message to the topic the consumer subscribed
4. the consumer client works well and get the message the producer produced
5. and then stop the consumer client
6. produce a message agin
7. restart the consumer client with connection option `cleanSession=false`

At `step 7` I expect a message which is produced during the consuer client stop. But actually I do get the message `AND` and an exception like this:

```java
org.eclipse.paho.client.mqttv3.MqttException: 已断开连接
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:181)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:133)
	... 7 common frames omitted
```

And after this exception occurring, when I restart the consumer client, and produce message to the topic the consumer subscribed, **the consumer cannot receive message from the topic any more (with the session alived)**

Here is the all error log I got from emqx broker:

```java
2020-10-19 14:59:16.135 [error] xgd@@@TEST-CSJ crasher:
    initial call: emqx_session:init/1
    pid: <0.20803.7994>
    registered_name: []
    exception error: no match of right hand side value true
      in function  emqx_session:dispatch/2 (src/emqx_session.erl, line 853)
      in call from emqx_session:dequeue2/1 (src/emqx_session.erl, line 945)
      in call from emqx_session:handle_cast/2 (src/emqx_session.erl, line 559)
      in call from gen_server:try_dispatch/4 (gen_server.erl, line 637)
      in call from gen_server:handle_msg/6 (gen_server.erl, line 711)
    ancestors: [emqx_session_sup,emqx_sm_sup,emqx_sup,<0.1351.0>]
    message_queue_len: 0
    messages: []
    links: [<0.22122.4294>,<38461.18766.5584>]
    dictionary: [{enqueue_stats,1},
                  {'$logger_metadata$',#{client_id => <<"xgd@@@TEST-CSJ">>}},
                  {deliver_stats,7},
                  {force_shutdown_policy,
                      #{max_heap_size => 0,message_queue_len => 0}}]
    trap_exit: true
    status: running
    heap_size: 17731
    stack_size: 27
    reductions: 497868
  neighbours:
    neighbour:
      pid: <38461.18766.5584>
      registered_name: []
      initial call: emqx_connection:init/1
      current_function: {gen_server,loop,7}
      ancestors: [<38461.1561.0>,<38461.1560.0>,esockd_sup,<38461.1325.0>]
      message_queue_len: 0
      links: [#Port<38461.94884198>,<0.20803.7994>,<38461.1561.0>]
      trap_exit: false
      status: waiting
      heap_size: 2586
      stack_size: 10
      reductions: 5127
      current_stacktrace: [{gen_server,loop,7,[{file,"gen_server.erl"},{line,403}]},
                  {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,249}]}]



2020-10-19 14:59:16.102 [error] xgd@@@TEST-CSJ ** Generic server <0.20803.7994> terminating
** Last message in was {'$gen_cast',
                           {resume,
                               #{clean_start => false,
                                 client_id => <<"xgd@@@TEST-CSJ">>,
                                 conn_pid => <38461.18766.5584>,
                                 expiry_interval => 7200,max_inflight => 1000,
                                 topic_alias_maximum => 0,
                                 username => <<"TEST-CSJ">>,
                                 will_msg => undefined,zone => external}}}



                                 
2020-10-19 14:59:16.102 [error] xgd@@@TEST-CSJ ** Generic server <0.20803.7994> terminating
** Last message in was {'$gen_cast',
                           {resume,
                               #{clean_start => false,
                                 client_id => <<"xgd@@@TEST-CSJ">>,
                                 conn_pid => <38461.18766.5584>,
                                 expiry_interval => 7200,max_inflight => 1000,
                                 topic_alias_maximum => 0,
                                 username => <<"TEST-CSJ">>,
                                 will_msg => undefined,zone => external}}}
** When Server state == {state,15000,false,local,<<"xgd@@@TEST-CSJ">>,
                         <<"TEST-CSJ">>,undefined,undefined,7,0,
                         #{<<"iot/radio/TEST-CSJ">> =>
                            #{nl => 0,qos => 1,rap => 0,rc => 0,rh => 0}},
                         false,
                         {emqx_inflight,1000,{0,nil}},
                         20000,undefined,
                         {mqueue,true,1000,1,0,none,infinity,
                          {queue,
                           [{message,
                             <<0,5,178,0,166,158,161,165,14,135,204,30,116,8,0,
                               1>>,
                             1,<<"radioServer">>,
                             #{dup => false,retain => false},
                             #{username => <<"radioServer">>},
                             <<"iot/radio/TEST-CSJ">>,
                             <<"{\n  \"data\": {\n    \"merch_no\": \"84944037011A00O\",\n    \"merch_name\": \"Â¶ÄÈ¶È¼Ù´å\",\n    \"term_no\": \"Q5000503\",\n    \"amount\": \"999\",\n    \"batch_no\": \"\",\n    \"vouch_no\": \"\",\n    \"description\": \"ÒµÎñÀàÐÍ£º´«Ã½\",\n    \"pay_type\": \"3\",\n    \"trans_time\": \"2020-10-19 14:59:07\",\n    \"term_sn\": \"EQR1000673\",\n    \"order_id\": \"20200728171133629\",\n    \"refer_no\": \"091040105136\"\n  },\n  \"create_time\": \"20201019145907\",\n  \"msg_type\": \"print\",\n  \"msg_id\": \"2020072817113362559\"\n}">>,
                             {1603,90748,711334}}],
                           [],1}},
                         #{},100,300000,undefined,7200,
                         #Ref<0.2999840048.2238971906.153444>,true,undefined,
                         {emqx_gc,
                          #{cnt => {1000,1000},oct => {1048576,1048576}}},
                         {1603,90634,446117},
                         undefined,undefined}
** Reason for termination ==
** {{badmatch,true},
    [{emqx_session,dispatch,2,[{file,"src/emqx_session.erl"},{line,853}]},
     {emqx_session,dequeue2,1,[{file,"src/emqx_session.erl"},{line,945}]},
     {emqx_session,handle_cast,2,[{file,"src/emqx_session.erl"},{line,559}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
     {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
```

And the code I tested :

```java
// consumer
MqttClient client = new MqttClient(broker, clientId, persistence);

MqttConnectOptions connOpts = new MqttConnectOptions();
connOpts.setUserName("***");
connOpts.setPassword("***".toCharArray());

connOpts.setCleanSession(false);
connOpts.setAutomaticReconnect(true);
connOpts.setKeepAliveInterval(5);

client.setCallback(new OnMessageCallback());

log.info(("Connecting to broker: " + broker));
IMqttToken mqttToken = client.connectWithResult(connOpts);


if (mqttToken.getSessionPresent()) {
    log.info(("Connected with session"));
} else {
    log.info(("Connected without session"));
    client.subscribe(subTopic);
}

// producer
MqttClient client = new MqttClient(broker, clientId, persistence);


MqttConnectOptions connOpts = new MqttConnectOptions();
connOpts.setUserName("***");
connOpts.setPassword("***".toCharArray());

connOpts.setCleanSession(false);
connOpts.setAutomaticReconnect(false);
connOpts.setKeepAliveInterval(5);
connOpts.setConnectionTimeout(5);


client.setCallback(new OnMessageCallback());


log.info(("Connecting to broker: " + broker));
client.connect(connOpts);
log.info(("Connected"));

String msg = UUID.randomUUID().toString();


MqttMessage message = new MqttMessage(msg.getBytes());
message.setQos(1);
message.setRetained(false);

client.publish(pubTopic, message);
log.info("topic {} Published message: {}", pubTopic, msg);

client.disconnect();
log.info(("Disconnected"));
client.close();
System.exit(0);
```

**Comment by tigercl** [comment]
@RichardChengshaojin It seems that this is caused by a bug in the v3.0.1, I suggest you upgrade to the more stable v3.2.7.

**Comment by HJianBo** [comment]
Agreed, After the Session crashes, the client can no longer accept offline messages:

https://github.com/emqx/emqx/blob/00863acea370e0367824201c6bc850515ada1889/src/emqx_session.erl#L853

You can try to upgrade to v3.2.7, or modify the following code and recompile emqx:

https://github.com/emqx/emqx/blob/00863acea370e0367824201c6bc850515ada1889/src/emqx_session.erl#L888-L889

to
```
do_deliver(PacketId, Msg, #state{conn_pid = ConnPid, binding = remote}) ->
    emqx_rpc:cast(node(ConnPid), erlang, send, [ConnPid, {deliver, {publish, PacketId, Msg}}]), ok.
```

**Comment by RichardChengshaojin** [comment]
@tigercl; Exactly v3.0.1. 
@HJianBo 
thanks

But It takes a lot to upgrade the emqx cluster used in productive environment.
btw, this problem happens in productive environment. But it works well in my development environment with the same version.
Maybe there is something wrong when I build my **emqx cluster** ?

**Comment by HJianBo** [comment]
It only occurs when delivering a message to another node in the cluster, e.g., when the client posts a message for a topic, but the topic has subscriptions on other nodes in the cluster.

So, there is a Plan B that you can fix and recompile it with OTP 21 (The version of OTP should be the same as the version used by emqx v3.0.1.), then try to hot update it.

you can see: 
- [Code Replacement in Erlang](http://erlang.org/doc/reference_manual/code_loading.html#code-replacement)
- [Erlang 热更新](https://www.cnblogs.com/me-sa/archive/2011/10/29/erlang0010.html)

Of course, you need to verify that the problem can be reproduced and solved in the test environment first.

**Comment by RichardChengshaojin** [comment]
@HJianBo 
Yes I have reproduced  this problem in my test environment.

1. Firstly I subscribe a topic with `cleanSession=false`, the consumer connected to the node A;
2. And the I restart the consumer with `cleanSession=false`, the consumer connected to the node B;
3. The result is that the consumer cannot receive any message from the topic anymore.
4. But with the options `cleanSession=true`, it can works well.

Is it a bug in v3.0.1, so I need to upgrade the version ?

**Comment by HJianBo** [comment]
Yes, you can update to the nearby stable version v3.2.7.

**Comment by RichardChengshaojin** [comment]
@HJianBo Yes we are trying to upgrade. thanks~

**Comment by RichardChengshaojin** [comment]
@HJianBo  

I download emqx from [https://www.emqx.io/downloads/broker/v3.2.7/emqx-centos7-v3.2.7.x86_64.rpm](https://www.emqx.io/downloads/broker/v3.2.7/emqx-centos7-v3.2.7.x86_64.rpm)

- and get the pkg: **emqx-centos7-v3.2.7.x86_64.rpm**
- and then install `rpm -ivh emqx-centos7-v3.2.7.x86_64.rpm`
- but when I start emqx broker, I get the version as below:
```java
./emqx start
emqx 3.0.1 is started successfully!
```

what happend to the version ?
