### ISSUE TITLE
emqx manual docker image: Kernel pid terminated

### ISSUE THREAD

**Issue by auror** [emqx/emqx#4422]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): Node '522466e19fab@XXXXX' not responding to pings.
- Hardware configuration (e.g. `lscpu`): 8
- OS (e.g. `cat /etc/os-release`): 
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.4
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
- Kernel (e.g. `uname -a`): Linux 522466e19fab 4.19.121-linuxkit #1 SMP Thu Jan 21 15:36:34 UTC 2021 x86_64 Linux
- Erlang/OTP version (in case you build emqx from source code):  23
- Others:

**What happened and what you expected to happen**:
We manually tried to build and run docker image of emqx. The image was built successfully, but the process exited with the following error
```
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,jiffy}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,jiffy}}},{kernel,start,[normal,[]]}}})

Crash dump is being written to: log/crash.dump...done
```

**How to reproduce it (as minimally and precisely as possible)**:
`make docker-build`
`docker run -it emqx/emqx:build-alpine-amd64 -- sh`
`/opt/emqx $ ./bin/emqx console`

Error:
```
++++ readlink ./bin/emqx
++++ echo ./bin/emqx
+++ dirname ./bin/emqx
++ cd ./bin/..
++ pwd -P
+ ROOT_DIR=/opt/emqx
+ . /opt/emqx/releases/emqx_vars
++ REL_VSN=4.3-beta.1-189079f8
++ ERTS_VSN=11.1.8
++ ERL_OPTS=
+++++ readlink ./bin/emqx
+++++ echo ./bin/emqx
++++ dirname ./bin/emqx
+++ cd ./bin/..
+++ pwd -P
++ RUNNER_ROOT_DIR=/opt/emqx
++ RUNNER_BIN_DIR=/opt/emqx/bin
++ RUNNER_LOG_DIR=/opt/emqx/log
++ RUNNER_LIB_DIR=/opt/emqx/lib
++ RUNNER_ETC_DIR=/opt/emqx/etc
++ RUNNER_DATA_DIR=/opt/emqx/data
++ RUNNER_USER=
+++ grep ekka /opt/emqx/releases/RELEASES
+++ awk -F '\"' '{print $2}'
++ LIB_EKKA_DIR=/opt/emqx/lib/ekka-0.8.0
++ EMQX_LICENSE_CONF=
++ export 'EMQX_DESCRIPTION=EMQ X Broker'
++ EMQX_DESCRIPTION='EMQ X Broker'
++ REL_NAME=emqx
++ ERTS_PATH=/opt/emqx/erts-11.1.8/bin
+ RUNNER_SCRIPT=/opt/emqx/bin/emqx
+ CODE_LOADING_MODE=embedded
+ REL_DIR=/opt/emqx/releases/4.3-beta.1-189079f8
++ whoami
+ WHOAMI=emqx
+ mkdir -p /opt/emqx/log
+ mkdir -p /opt/emqx/data
+ export CUTTLEFISH_ENV_OVERRIDE_PREFIX=EMQX_
+ CUTTLEFISH_ENV_OVERRIDE_PREFIX=EMQX_
+ check_user console
+ '[' '' ']'
+ ES=0
+ '[' 0 -ne 0 ']'
+ '[' -z '' ']'
+ EPMD_ARG='-start_epmd false -epmd_module ekka_epmd -proto_dist ekka'
++ ulimit -n
+ ULIMIT_F=1048576
+ '[' 1048576 -lt 1024 ']'
+ CUTTLEFISH=yes
+ SED_REPLACE='sed -i '
+ case $(sed --help 2>&1) in
++ sed --help
+ SED_REPLACE='sed -i '
+ '[' -z '' ']'
+ '[' -f /opt/emqx/etc/sys.config ']'
+ RELX_CONFIG_PATH=
+ '[' -z '' ']'
+ NODENAME=522466e19fab@172.17.0.3
+ '[' -z 522466e19fab@172.17.0.3 ']'
+ '[' -z 522466e19fab@172.17.0.3 ']'
+ NAME_ARG='-name 522466e19fab@172.17.0.3'
++ echo '-name 522466e19fab@172.17.0.3'
++ awk '{print $1}'
+ NAME_TYPE=-name
++ echo '-name 522466e19fab@172.17.0.3'
++ awk '{print $2}'
+ NAME=522466e19fab@172.17.0.3
++ echo 522466e19fab@172.17.0.3
++ awk -F@ '{print $1}'
+ NODENAME=522466e19fab
+ export ESCRIPT_NAME=522466e19fab
+ ESCRIPT_NAME=522466e19fab
+ PIPE_DIR=//opt/emqx/data/emqx_erl_pipes/522466e19fab@172.17.0.3/
+ '[' -z '' ']'
+ COOKIE=
+ '[' -z '' ']'
++ grep -E '^[ \t]*node.cookie[ \t]*=[ \t]*' /opt/emqx/etc/emqx.conf
++ tail -1
++ cut -d = -f 2-
+ COOKIE=' ABCCOOKIE'
+ '[' -z ' ABCCOOKIE' ']'
+ COOKIE_ARG='-setcookie  ABCCOOKIE'
++ echo '-setcookie  ABCCOOKIE'
++ awk '{print $2}'
+ COOKIE=ABCCOOKIE
++ grep -E '^[ \t]*cluster.proto_dist[ \t]*=[ \t]*' /opt/emqx/etc/emqx.conf
++ tail -1
++ cut -d = -f 2-
+ PROTO_DIST=' inet_tcp'
+ '[' -z ' inet_tcp' ']'
+ PROTO_DIST_ARG='-proto_dist  inet_tcp'
+ export ROOTDIR=/opt/emqx
+ ROOTDIR=/opt/emqx
+ export ERTS_DIR=/opt/emqx/erts-11.1.8
+ ERTS_DIR=/opt/emqx/erts-11.1.8
+ export BINDIR=/opt/emqx/erts-11.1.8/bin
+ BINDIR=/opt/emqx/erts-11.1.8/bin
+ export EMU=beam
+ EMU=beam
+ export PROGNAME=erl
+ PROGNAME=erl
+ export LD_LIBRARY_PATH=/opt/emqx/erts-11.1.8/lib:
+ LD_LIBRARY_PATH=/opt/emqx/erts-11.1.8/lib:
+ ERTS_LIB_DIR=/opt/emqx/erts-11.1.8/../lib
+ MNESIA_DATA_DIR=/opt/emqx/data/mnesia/522466e19fab@172.17.0.3
+ cd /opt/emqx
+ case $NAME in
+ case "$1" in
+ bootstrapd
+ '[' -e /opt/emqx/data/.erlang.cookie ']'
+ case "$1" in
+ '[' -f /opt/emqx/releases/4.3-beta.1-189079f8/emqx.boot ']'
+ BOOTFILE=/opt/emqx/releases/4.3-beta.1-189079f8/start
+ '[' '' = '' ']'
+ export EMQX_LOG__TO=console
+ EMQX_LOG__TO=console
+ generate_config
+ rm -rf '/opt/emqx/log/*.siz'
+ '[' yes '!=' yes ']'
+ EMQX_LICENSE_CONF_OPTION=
+ '[' '' '!=' '' ']'
++ /opt/emqx/erts-11.1.8/bin/escript /opt/emqx/bin/cuttlefish -i /opt/emqx/releases/4.3-beta.1-189079f8/emqx.schema -c /opt/emqx/etc/emqx.conf -d /opt/emqx/data/configs generate
+ CONFIG_ARGS=' -config /opt/emqx/data/configs/app.2021.03.23.15.18.56.config -args_file /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args -vm_args /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args '
++ echo ' -config /opt/emqx/data/configs/app.2021.03.23.15.18.56.config -args_file /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args -vm_args /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args '
++ sed -n 's/^.*\(vm_args[[:space:]]\)//p'
++ awk '{print $1}'
+ CUTTLE_GEN_ARG_FILE=/opt/emqx/data/configs/vm.2021.03.23.15.18.56.args
+ TMP_ARG_FILE=/opt/emqx/data/configs/vm.args.tmp
+ cp /opt/emqx/etc/vm.args /opt/emqx/data/configs/vm.args.tmp
+ echo ''
+ echo '-pa /opt/emqx/releases/4.3-beta.1-189079f8/consolidated'
+ sed '/^#/d' /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args
+ sed '/^$/d'
+ IFS=
+ read -r ARG_LINE
++ echo '-env ERL_CRASH_DUMP log/crash.dump'
++ awk '{$NF="";print}'
+ ARG_KEY='-env ERL_CRASH_DUMP '
++ echo '-env ERL_CRASH_DUMP log/crash.dump'
++ awk '{print $NF}'
+ ARG_VALUE=log/crash.dump
++ awk '{print $NF}'
++ grep '^-env ERL_CRASH_DUMP ' /opt/emqx/data/configs/vm.args.tmp
+ TMP_ARG_VALUE=
+ '[' log/crash.dump '!=' '' ']'
+ '[' -n '' ']'
+ echo '-env ERL_CRASH_DUMP log/crash.dump'
+ IFS=
+ read -r ARG_LINE
++ echo '+e 2097152'
++ awk '{$NF="";print}'
+ ARG_KEY='+e '
++ echo '+e 2097152'
++ awk '{print $NF}'
+ ARG_VALUE=2097152
++ grep '^+e ' /opt/emqx/data/configs/vm.args.tmp
++ awk '{print $NF}'
+ TMP_ARG_VALUE=262144
+ '[' 2097152 '!=' 262144 ']'
+ '[' -n 262144 ']'
+ sh -c 'sed -i  '\''s/^+e .*$/+e 2097152/'\'' /opt/emqx/data/configs/vm.args.tmp'
+ IFS=
+ read -r ARG_LINE
++ echo '-env ERL_FULLSWEEP_AFTER 1000'
++ awk '{$NF="";print}'
+ ARG_KEY='-env ERL_FULLSWEEP_AFTER '
++ echo '-env ERL_FULLSWEEP_AFTER 1000'
++ awk '{print $NF}'
+ ARG_VALUE=1000
++ grep '^-env ERL_FULLSWEEP_AFTER ' /opt/emqx/data/configs/vm.args.tmp
++ awk '{print $NF}'
+ TMP_ARG_VALUE=1000
+ '[' 1000 '!=' 1000 ']'
+ IFS=
+ read -r ARG_LINE
++ echo '+Q 1048576'
++ awk '{$NF="";print}'
+ ARG_KEY='+Q '
++ echo '+Q 1048576'
++ awk '{print $NF}'
+ ARG_VALUE=1048576
++ grep '^+Q ' /opt/emqx/data/configs/vm.args.tmp
++ awk '{print $NF}'
+ TMP_ARG_VALUE=1048576
+ '[' 1048576 '!=' 1048576 ']'
+ IFS=
+ read -r ARG_LINE
++ echo '+P 2097152'
++ awk '{$NF="";print}'
+ ARG_KEY='+P '
++ echo '+P 2097152'
++ awk '{print $NF}'
+ ARG_VALUE=2097152
++ ++ awk grep '{print $NF}''^+P ' 
/opt/emqx/data/configs/vm.args.tmp
+ TMP_ARG_VALUE=2097152
+ '[' 2097152 '!=' 2097152 ']'
+ IFS=
+ read -r ARG_LINE
++ echo '-setcookie ABCCOOKIE'
++ awk '{$NF="";print}'
+ ARG_KEY='-setcookie '
++ echo '-setcookie ABCCOOKIE'
++ awk '{print $NF}'
+ ARG_VALUE=ABCCOOKIE
++ grep '^-setcookie ' /opt/emqx/data/configs/vm.args.tmp
++ awk '{print $NF}'
+ TMP_ARG_VALUE=
+ '[' ABCCOOKIE '!=' '' ']'
+ '[' -n '' ']'
+ echo '-setcookie ABCCOOKIE'
+ IFS=
+ read -r ARG_LINE
+ '[' -n '-name 522466e19fab@172.17.0.3' ']'
++ echo '-name 522466e19fab@172.17.0.3'
++ awk '{$NF="";print}'
+ ARG_KEY='-name '
++ echo '-name 522466e19fab@172.17.0.3'
++ awk '{print $NF}'
+ ARG_VALUE=522466e19fab@172.17.0.3
++ ++ grep '^-name ' /opt/emqx/data/configs/vm.args.tmpawk 
'{print $NF}'
+ TMP_ARG_VALUE=
+ '[' 522466e19fab@172.17.0.3 '!=' '' ']'
+ '[' -n '' ']'
+ echo '-name 522466e19fab@172.17.0.3'
+ IFS=
+ read -r ARG_LINE
+ '[' -n '' ']'
+ sh -c 'sed -i  '\''s/ENV_REL_VSN/4.3-beta.1-189079f8/g'\'' /opt/emqx/data/configs/vm.args.tmp'
+ mv -f /opt/emqx/data/configs/vm.args.tmp /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args
+ relx_nodetool chkconfig -config /opt/emqx/data/configs/app.2021.03.23.15.18.56.config -args_file /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args -vm_args /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args
+ command=chkconfig
+ shift
+ ERL_FLAGS=' -start_epmd false -epmd_module ekka_epmd -proto_dist ekka'
+ ERL_LIBS=/opt/emqx/lib/ekka-0.8.0:
+ /opt/emqx/erts-11.1.8/bin/escript /opt/emqx/bin/nodetool -name 522466e19fab@172.17.0.3 -setcookie ABCCOOKIE chkconfig -config /opt/emqx/data/configs/app.2021.03.23.15.18.56.config -args_file /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args -vm_args /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args
+ EMU=beam
+ PROGNAME=bin/emqx
+ export EMU
+ export PROGNAME
+ ARGS=console
+ set -- /opt/emqx/erts-11.1.8/bin/erlexec -boot /opt/emqx/releases/4.3-beta.1-189079f8/start -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-11.1.8/../lib -mnesia dir '"/opt/emqx/data/mnesia/522466e19fab@172.17.0.3"' -config /opt/emqx/data/configs/app.2021.03.23.15.18.56.config -args_file /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args -vm_args /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka
+ echo 'Exec: /opt/emqx/erts-11.1.8/bin/erlexec -boot /opt/emqx/releases/4.3-beta.1-189079f8/start -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-11.1.8/../lib -mnesia dir "/opt/emqx/data/mnesia/522466e19fab@172.17.0.3" -config /opt/emqx/data/configs/app.2021.03.23.15.18.56.config -args_file /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args -vm_args /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka' -- console
Exec: /opt/emqx/erts-11.1.8/bin/erlexec -boot /opt/emqx/releases/4.3-beta.1-189079f8/start -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-11.1.8/../lib -mnesia dir "/opt/emqx/data/mnesia/522466e19fab@172.17.0.3" -config /opt/emqx/data/configs/app.2021.03.23.15.18.56.config -args_file /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args -vm_args /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
+ echo 'Root: /opt/emqx'
Root: /opt/emqx
+ echo /opt/emqx
/opt/emqx
+ logger -t '' 'Starting up'
+ exec /opt/emqx/erts-11.1.8/bin/erlexec -boot /opt/emqx/releases/4.3-beta.1-189079f8/start -mode embedded -boot_var ERTS_LIB_DIR /opt/emqx/erts-11.1.8/../lib -mnesia dir '"/opt/emqx/data/mnesia/522466e19fab@172.17.0.3"' -config /opt/emqx/data/configs/app.2021.03.23.15.18.56.config -args_file /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args -vm_args /opt/emqx/data/configs/vm.2021.03.23.15.18.56.args -start_epmd false -epmd_module ekka_epmd -proto_dist ekka -- console
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:8:8] [ds:8:8:8] [async-threads:4]

{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,jiffy}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,jiffy}}},{kernel,start,[normal,[]]}}})

Crash dump is being written to: log/crash.dump...done
```

**Anything else we need to know?**:

**Comment by auror** [comment]
Not sure if it's the issue with `alpine` or something else. or are we missing something here ?
cc: @zmstone

**Comment by zmstone** [comment]
it has failed to load jiffy
which is likely due the binary is not built or built on a different platform.
have you tried `make clean` before make docker ?

**Comment by auror** [comment]
@zmstone Yes, but that didn't help the elixir deps
```
#13 37.10 ===> Compiling mime
#13 38.11 ** (File.Error) could not get current working directory nil: no such file or directory
#13 38.11     (elixir 1.11.4) lib/file.ex:1502: File.cwd!/0
#13 38.11     (elixir 1.11.4) lib/path.ex:161: Path.expand/1
#13 38.11     (elixir 1.11.4) lib/code.ex:234: Code.prepend_path/1
#13 38.11     (mix 1.11.4) lib/mix/tasks/loadpaths.ex:41: Mix.Tasks.Loadpaths.run/1
#13 38.11     (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
#13 38.11     (mix 1.11.4) lib/mix/tasks/compile.ex:113: Mix.Tasks.Compile.run/1
#13 38.11     (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
#13 38.11     (mix 1.11.4) lib/mix/cli.ex:84: Mix.CLI.run_task/2
#13 38.21 ===> Failed to compile application mime with mix
#13 38.23 make: *** [Makefile:71: emqx] Error 1
------
```

But will try to clean the complete destination directory `_build` & check

Regards

**Comment by zmstone** [comment]
You can delete the elixir dependency dirs from `_build/default`
if you have to repeat `make clean-all` a lot.

**Comment by auror** [comment]
Cool @zmstone It worked 👍
