### ISSUE TITLE
when deploy docker compose, springboot cannot connect to the emqx 1883 tcp port

### ISSUE THREAD

**Issue by Sakura-gh** [emqx/emqx#5085]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I want to deploy my springboot, mysql, redis, emqx by docker compose. The problem is, the springboot cannot connect to the  tcp://emqx:1883. (the program can run successfully in my local machine, and the code should be true, I just adjust the .properties file to change tcp://localhost:1883 to tcp://emqx:1883, for docker usage)
~~~bash
# error log
准备连接到broker：tcp://emqx:1883
connect to broker error!
Unable to connect to server (32103) - java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:80)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74)
	... 2 more
~~~

But when I enter the springboot docker,  try to access emqx docker, I can directly access the emqx:1883 by `wget`, like this:
~~~bash
gehao@web:~$ sudo docker ps -a
CONTAINER ID   IMAGE              COMMAND                  CREATED              STATUS              PORTS                                                                                                                                                           NAMES
d7febb11164a   iotserver_webapp   "java -jar /iotserve…"   About a minute ago   Up About a minute   0.0.0.0:8443->8443/tcp                                                                                                                                          iotserver
dc92ceaa6ad2   redis:6.2.1        "docker-entrypoint.s…"   About a minute ago   Up About a minute   0.0.0.0:6379->6379/tcp                                                                                                                                          iot_redis
44cb4fe0d839   emqx/emqx:v4.0.0   "/usr/bin/docker-ent…"   About a minute ago   Up About a minute   4369/tcp, 5369/tcp, 6369/tcp, 0.0.0.0:1883->1883/tcp, 0.0.0.0:8083-8084->8083-8084/tcp, 8080/tcp, 0.0.0.0:8883->8883/tcp, 0.0.0.0:18083->18083/tcp, 11883/tcp   iot_emqx
a7bfd00af1f4   mysql:8.0.24       "docker-entrypoint.s…"   About a minute ago   Up About a minute   0.0.0.0:3306->3306/tcp, 33060/tcp                                                                                                                               iot_mysql
fe2ffc59cc01   ubuntu:18.04       "/bin/bash"              6 hours ago          Up 6 hours                                                                                                                                                                          boorish_grommet
gehao@web:~$ sudo docker exec -it iotserver bash
root@d7febb11164a:/# wget emqx:1883
--2021-06-24 07:42:24--  http://emqx:1883/
Resolving emqx (emqx)... 172.30.0.4
Connecting to emqx (emqx)|172.30.0.4|:1883... connected.
HTTP request sent, awaiting response... No data received.
Retrying.
~~~

I can also access the http://ip:18083 in my local browser. 
![image](https://user-images.githubusercontent.com/50900131/123224434-640b9c00-d504-11eb-90e6-c74c87217971.png)

It shows that the emqx runs properly, but why the springboot cannot connect to its 1883 tcp port?

my docker-compose yml:
~~~yml
version: "3"

services:
  webapp:
    build: . # Dockerfile文件路径, 注意是目录名, 而不是文件名
    container_name: iotserver # 容器名
    restart: always
    depends_on:
      - emqx
      - mysql
      - redis
    ports:
      - "8443:8443"

  emqx:
    image: emqx/emqx:v4.0.0
    container_name: iot_emqx
    restart: always
    ports:
    - "1883:1883"
    - "18083:18083"
    - "8883:8883"
    - "8083:8083"
    - "8084:8084"
    
    ...
~~~

my emqx configuration:
~~~bash
iot.broker=tcp://emqx:1883
iot.topic=testapp
iot.timeout=2000
iot.keepAlive=20
iot.isCleanSession=true
iot.qos=2
iot.clientID=server
~~~

**Comment by sh3d2** [comment]
hi @Sakura-gh 

are you retrying to connect in your springboot app after that initial `Connection refused` or is it just one try?
My best guess is that you try to connect before emqx listeners are started.

**Comment by Sakura-gh** [comment]
> hi @Sakura-gh
> 
> are you retrying to connect in your springboot app after that initial `Connection refused` or is it just one try?
> My best guess is that you try to connect before emqx listeners are started.

you are right, the emqx start need 28 seconds, and the `depends on` params in docker-compose just starts containers in dependency order, but not ensures the service has started.

I use script to listen the emqx tcp port and then start the springboot, the problem will be solved:
~~~bash
wait-for-it.sh: waiting 60 seconds for emqx:1883
wait-for-it.sh: emqx:1883 is available after 28 seconds

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.1.RELEASE)
~~~
