### ISSUE TITLE
SSL Handshaking error

### ISSUE THREAD

**Issue by webfrank** [emqx/emqx#9679]
### What happened?

I'm using siddhi.io application, a JAVA CEP, connecting to EMQX using SSL and I receive this error:

`{ssl_error,{tls_alert,{insufficient_security,"TLS server: In state start at tls_handshake_1_3.erl:2162 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_groups"}}}`

From Java side I have this error
```
Caused by: MqttException (0) - javax.net.ssl.SSLHandshakeException: Received fatal alert: insufficient_security
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
```

siddhi.io mqtt library is paho.

### What did you expect to happen?

As with different clients I expect the Java one to connect without issues. I've checked for the presence of the CA root and it is ok. I'm using a Let's Encrypt certificate.

### How can we reproduce it (as minimally and precisely as possible)?

Configure a SSL listener with a valid Let's Encrypt certificate.
Start the latest version of siddhi.io (5.1.3) and configure a MQTT source using SSL.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.0.13
datetime  : 2023-01-04T16:42:20.836590005+00:00
uptime    : 1 days, 7 hours, 23 minutes, 50 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux emqx-replicant-5b9c9689bc-fdd9j 5.4.172-90.336.amzn2.x86_64 #1 SMP Wed Jan 19 23:08:01 UTC 2022 x86_64 GNU/Linux

```

</details>

### Log files

<details>
```
2023-01-04T16:11:43.776146+00:00 [error] supervisor: 'esockd_connection_sup - <0.5483.83>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{insufficient_security,"TLS server: In state start at tls_handshake_1_3.erl:2162 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_groups"}}}, offender: [{pid,<0.20241.84>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,limiter => #{bytes_in => #{capacity => 1099511627776,initial => 0,rate => infinity},client => #{bytes_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},connection => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_routing => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity}},connection => #{capacity => 1000,initial => 0,rate => 100.0},message_in => #{capacity => 1099511627776,initial => 0,rate => infinity},message_routing => #{capacity => 1099511627776,initial => 0,rate => infinity}},listener => {ssl,default},zone => default}]}}]
2023-01-04T16:11:59.512987+00:00 [error] supervisor: 'esockd_connection_sup - <0.5483.83>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{insufficient_security,"TLS server: In state start at tls_handshake_1_3.erl:2162 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_groups"}}}, offender: [{pid,<0.11810.85>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,limiter => #{bytes_in => #{capacity => 1099511627776,initial => 0,rate => infinity},client => #{bytes_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},connection => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_routing => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity}},connection => #{capacity => 1000,initial => 0,rate => 100.0},message_in => #{capacity => 1099511627776,initial => 0,rate => infinity},message_routing => #{capacity => 1099511627776,initial => 0,rate => infinity}},listener => {ssl,default},zone => default}]}}]
2023-01-04T16:11:59.714332+00:00 [error] supervisor: 'esockd_connection_sup - <0.5483.83>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{insufficient_security,"TLS server: In state start at tls_handshake_1_3.erl:2162 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_groups"}}}, offender: [{pid,<0.12133.85>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,limiter => #{bytes_in => #{capacity => 1099511627776,initial => 0,rate => infinity},client => #{bytes_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},connection => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_routing => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity}},connection => #{capacity => 1000,initial => 0,rate => 100.0},message_in => #{capacity => 1099511627776,initial => 0,rate => infinity},message_routing => #{capacity => 1099511627776,initial => 0,rate => infinity}},listener => {ssl,default},zone => default}]}}]
2023-01-04T16:13:47.506408+00:00 [error] supervisor: 'esockd_connection_sup - <0.5483.83>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{insufficient_security,"TLS server: In state start at tls_handshake_1_3.erl:2162 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_groups"}}}, offender: [{pid,<0.5248.91>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,limiter => #{bytes_in => #{capacity => 1099511627776,initial => 0,rate => infinity},client => #{bytes_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},connection => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_routing => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity}},connection => #{capacity => 1000,initial => 0,rate => 100.0},message_in => #{capacity => 1099511627776,initial => 0,rate => infinity},message_routing => #{capacity => 1099511627776,initial => 0,rate => infinity}},listener => {ssl,default},zone => default}]}}]
2023-01-04T16:14:48.187844+00:00 [error] supervisor: 'esockd_connection_sup - <0.5483.83>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{insufficient_security,"TLS server: In state start at tls_handshake_1_3.erl:2162 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_groups"}}}, offender: [{pid,<0.28733.92>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,limiter => #{bytes_in => #{capacity => 1099511627776,initial => 0,rate => infinity},client => #{bytes_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},connection => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_routing => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity}},connection => #{capacity => 1000,initial => 0,rate => 100.0},message_in => #{capacity => 1099511627776,initial => 0,rate => infinity},message_routing => #{capacity => 1099511627776,initial => 0,rate => infinity}},listener => {ssl,default},zone => default}]}}]
2023-01-04T16:21:49.886776+00:00 [error] supervisor: 'esockd_connection_sup - <0.5483.83>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{insufficient_security,"TLS server: In state start at tls_handshake_1_3.erl:2162 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_groups"}}}, offender: [{pid,<0.30431.92>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,limiter => #{bytes_in => #{capacity => 1099511627776,initial => 0,rate => infinity},client => #{bytes_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},connection => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_routing => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity}},connection => #{capacity => 1000,initial => 0,rate => 100.0},message_in => #{capacity => 1099511627776,initial => 0,rate => infinity},message_routing => #{capacity => 1099511627776,initial => 0,rate => infinity}},listener => {ssl,default},zone => default}]}}]
2023-01-04T16:21:50.099628+00:00 [error] supervisor: 'esockd_connection_sup - <0.5483.83>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{insufficient_security,"TLS server: In state start at tls_handshake_1_3.erl:2162 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_groups"}}}, offender: [{pid,<0.30435.92>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,limiter => #{bytes_in => #{capacity => 1099511627776,initial => 0,rate => infinity},client => #{bytes_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},connection => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_routing => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity}},connection => #{capacity => 1000,initial => 0,rate => 100.0},message_in => #{capacity => 1099511627776,initial => 0,rate => infinity},message_routing => #{capacity => 1099511627776,initial => 0,rate => infinity}},listener => {ssl,default},zone => default}]}}]
2023-01-04T16:31:51.125958+00:00 [error] supervisor: 'esockd_connection_sup - <0.5483.83>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{insufficient_security,"TLS server: In state start at tls_handshake_1_3.erl:2162 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_groups"}}}, offender: [{pid,<0.513.97>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,limiter => #{bytes_in => #{capacity => 1099511627776,initial => 0,rate => infinity},client => #{bytes_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},connection => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_routing => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity}},connection => #{capacity => 1000,initial => 0,rate => 100.0},message_in => #{capacity => 1099511627776,initial => 0,rate => infinity},message_routing => #{capacity => 1099511627776,initial => 0,rate => infinity}},listener => {ssl,default},zone => default}]}}]
2023-01-04T16:31:51.406313+00:00 [error] supervisor: 'esockd_connection_sup - <0.5483.83>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{insufficient_security,"TLS server: In state start at tls_handshake_1_3.erl:2162 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_groups"}}}, offender: [{pid,<0.821.97>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,limiter => #{bytes_in => #{capacity => 1099511627776,initial => 0,rate => infinity},client => #{bytes_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},connection => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_routing => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity}},connection => #{capacity => 1000,initial => 0,rate => 100.0},message_in => #{capacity => 1099511627776,initial => 0,rate => infinity},message_routing => #{capacity => 1099511627776,initial => 0,rate => infinity}},listener => {ssl,default},zone => default}]}}]
2023-01-04T16:36:51.791525+00:00 [error] supervisor: 'esockd_connection_sup - <0.5483.83>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{insufficient_security,"TLS server: In state start at tls_handshake_1_3.erl:2162 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_groups"}}}, offender: [{pid,<0.19613.113>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,limiter => #{bytes_in => #{capacity => 1099511627776,initial => 0,rate => infinity},client => #{bytes_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},connection => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_routing => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity}},connection => #{capacity => 1000,initial => 0,rate => 100.0},message_in => #{capacity => 1099511627776,initial => 0,rate => infinity},message_routing => #{capacity => 1099511627776,initial => 0,rate => infinity}},listener => {ssl,default},zone => default}]}}]
2023-01-04T16:41:52.552187+00:00 [error] supervisor: 'esockd_connection_sup - <0.5483.83>', errorContext: connection_shutdown, reason: {ssl_error,{tls_alert,{insufficient_security,"TLS server: In state start at tls_handshake_1_3.erl:2162 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_groups"}}}, offender: [{pid,<0.21662.129>},{name,connection},{mfargs,{emqx_connection,start_link,[#{enable_authn => true,limiter => #{bytes_in => #{capacity => 1099511627776,initial => 0,rate => infinity},client => #{bytes_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},connection => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_in => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity},message_routing => #{capacity => 1099511627776,divisible => false,failure_strategy => force,initial => 0,low_watermark => 0,max_retry_time => 10000,rate => infinity}},connection => #{capacity => 1000,initial => 0,rate => 100.0},message_in => #{capacity => 1099511627776,initial => 0,rate => infinity},message_routing => #{capacity => 1099511627776,initial => 0,rate => infinity}},listener => {ssl,default},zone => default}]}}]
```
</details>

**Comment by tigercl** [comment]
Hi @webfrank 
This error indicates that the (EC)DHE groups which the client supports don't match that of the server.

**Comment by tigercl** [comment]
TLS 1.3 introduces the "supported_groups" extension that is used for negotiating the Diffie-Hellman parameters in a TLS 1.3 handshake. Both client and server can specify a list of parameters that they are willing to use.

EMQX supports `x25519, x448, secp256r1, secp384r1` by default.

**Comment by webfrank** [comment]
Hi, just solved the issue. The standard image was using an old JDK, once upgraded the base image everything is working as expected.
Thank you for the support.
